spring:
  application:
    name: product-service
  profiles:
    active: localhost
  main:
    allow-bean-definition-overriding: true
info:
  component: Product Service

server:
  port: 9788
logging:                            #loglama seviyesi root olarak ayarlandı
  level:                            #property değeri DEBUG olarak ayarlandı
    root: off                       #DEBUG loglama seviyesi uygulamanın nasıl çalışacağı hakkında daha fazla bilgi sağlar
    com.example: DEBUG              #OFF: log mesajlarını göstermez ERROR: log hata mesajlarını gösterir WARN: uyarı mesajları INFO: INFO + WARN + ERROR
                                    #TRACE: tüm bilgi mesajları DEBUG: DEBUG + INFO + WARN + ERROR mesajları
                                    #root: off .....: DEBUG sadece ... olan paketteki logları gösterir

---
spring:
  profiles: localhost
  cloud:
    config:
      uri: http://localhost:8888
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: stock_management
  datasource:
    url: "jdbc:postgresql://postgres:5432/stock_management"
    username: postgres
    password: password

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

---
spring:
  profiles: stage
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: stock_management
  datasource:
    url: "jdbc:postgresql://postgres:5432/stock_management"
    username: postgres
    password: password

eureka:
  client:
    service-url:
      default-zone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    instance-id: ${spring.application.name}:${random.uuid}